Feature/kp/dashboard design
trentiums/expo-crm pull request #11
Opened 2024-09-02 05:35 UTC by kuldip-trentium

![Screenshot_20240902-110235_CRM](https://github.com/user-attachments/assets/010cc9d8-0720-426c-907e-626c3fe8dbae)

2024-09-02 07:46 UTC, Deeptrentium requested changes

2024-09-02 07:46 UTC, Deeptrentium commented on app/(protected)/(tabs)/tabs.style.ts
> +  color: #5892ff;
use theme

2024-09-03 11:25 UTC, Deepsutariya149 approved these changes

2024-09-03 11:58 UTC, Deeptrentium approved these changes

2024-09-03 12:07 UTC, sagark1510 requested changes

2024-09-04 12:21 UTC, sagark1510 approved these changes

2024-09-04 12:37 UTC, Deeptrentium requested changes

2024-09-04 12:37 UTC, Deeptrentium commented on app/(protected)/(tabs)/dashboard.tsx
> +    lead: DashboardLeadList;
DashboardLeadList = DashboardLeadsProps

2024-09-04 12:37 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.styles.ts
> +export const LeadDetailView = styled(View)`
use flexed from common style

2024-09-04 12:37 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +          onActionPress={() => onDeleteActionPress()}
handleDeleteLead()

2024-09-04 12:37 UTC, Deeptrentium commented on components/molecules/LeadStatus/LeadStatus.styles.ts
> +export const LeadStatusContainer = styled(View)<{ bgColor: string }>`
make it optional

2024-09-04 12:37 UTC, Deeptrentium commented on components/molecules/LeadsProgressChartItem/LeadsProgressChartItem.tsx
> +  useEffect(() => {
useEffect(() => {
    const containerHeight =
      maxValue && (item.progress / maxValue) * 70;
    height.value = withTiming(containerHeight || 0, { duration: 1000 });
  }, [item.progress, maxValue]);

2024-09-04 12:37 UTC, Deeptrentium commented on components/molecules/LeadsProgressChartItem/LeadsProgressChartItem.tsx
> +    borderWidth: item?.progress !== 0 ? 2 : undefined,
item?.progress && 2 || undefined,

2024-09-04 12:37 UTC, Deeptrentium commented on components/organisms/LeadsProgressChart/LeadsProgressChart.styles.ts
> +  height: ${({ height }) => `${height}px` || 'auto'};
its never goes in to ||

2024-09-04 12:37 UTC, Deeptrentium commented on components/organisms/UserDetailCard/UserDetailCard.styles.ts
> +  width: 50;
px missing

2024-09-04 12:37 UTC, Deeptrentium commented on components/templates/ScreenTemplate/ScreenTemplate.styles.ts
> +    backgroundColor ? backgroundColor : theme.colors.screenTemplateColor};
backgroundColor || theme.colors.screenTemplateColor

2024-09-04 13:15 UTC, merged