Feature/kp/product services design
trentiums/expo-crm pull request #15
Opened 2024-09-05 05:42 UTC by kuldip-trentium

![Screenshot_20240905-105411_CRM](https://github.com/user-attachments/assets/0d711ab7-0c4d-4046-81d4-2b1fcb191a94)
![Screenshot_20240905-105403_CRM](https://github.com/user-attachments/assets/7819a4ec-b380-417a-9d8f-c3a85e14a38b)
![Screenshot_20240905-105014_CRM](https://github.com/user-attachments/assets/22edefad-9b13-4ea3-9f86-6b9fb1127886)
![Screenshot_20240905-105022_CRM](https://github.com/user-attachments/assets/7d95ee8e-120b-44ec-ba9b-4f917cf06159)

2024-09-05 06:41 UTC, Deeptrentium requested changes

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/ActionModal/ActionModal.styles.ts
> +      ? theme.colors.BlueChaos
BlueChaos = blueChaos

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/ActionModal/ActionModal.tsx
> +                {loading && <Loader size={16} color={colors?.BlueChaos} />}
BlueChaos blueChaos

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +import Delete from '@atoms/Illustrations/Delete';
Delete - DeleteIcon

do this changes every where

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +              type: 'customToast',
enum

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +      if (status !== 'granted') {
add enum

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +          deleteLeadDocumentsAction({ media_id: deletedDocument?.[0]?.id }),
remove ?

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +          type: 'customToast',
enum

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +          type: 'customToast',
enum

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +            renderItem={({ item }) => (
merge both code in one condition

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +        router.navigate(`/(protected)/add-lead/${leadData?.id}`);
remove ?

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +            <WhatsAppContainer onPress={() => handleEmail(leadData?.email)}>
remove ?

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +            <WhatsAppContainer onPress={() => handlePhoneCall(leadData?.phone)}>
WhatsAppContainer = CommunicationOptionCon

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/LeadStatus/LeadStatus.tsx
> +      return <></>;
null

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/Search/Search.tsx
> +  const debouncedLeadSearch = useDebounce(search || undefined, 300);
300 must be come from constant

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/Search/Search.tsx
> +          textColor={colors?.textDark}
remove ?

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/TitleWithButton/TitleWithButton.styles.ts
> +  margin-top: ${({ top }) => top - 20 || 0}px;
update this

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/TitleWithButton/TitleWithButton.styles.ts
> +export const ButtonText = styled(Text)<{ textColor?: string }>`
add default color

2024-09-05 06:41 UTC, Deeptrentium commented on components/molecules/TitleWithButton/TitleWithButton.tsx
> +interface TitleWithButtonProps {
move it to props file

2024-09-05 06:41 UTC, Deeptrentium commented on components/organisms/AddProductForm/AddProductForm.tsx
> +      console.log(
remove log

2024-09-05 06:41 UTC, Deeptrentium commented on components/organisms/BasicInformatioForm/BasicInformationForm.styles.ts
> +    valid ? theme.colors.white : theme.colors.white};
add disable button color once UI updated

2024-09-05 06:41 UTC, Deeptrentium commented on components/organisms/UserDetailCard/UserDetailCard.tsx
> +            <EmailIcon color={colors?.gray} />
remove ?

2024-09-05 06:41 UTC, Deeptrentium commented on components/templates/ScreenTemplate/ScreenTemplate.tsx
> +            <PlusIcon color={colors?.bgColor} />
remove ?

2024-09-06 06:39 UTC, sagark1510 commented on app/(protected)/(tabs)/dashboard.tsx
> +        isShowSocialMedia
isShowSocialMedia = isSocialMediaVisible

2024-09-06 06:39 UTC, sagark1510 commented on app/(protected)/(tabs)/dashboard.tsx
> +    <ScreenTemplate isDrawerBtn>
isDrawerBtn = moreVisible

2024-09-06 06:40 UTC, sagark1510 commented on app/(protected)/(tabs)/leads.tsx
>      useState<RefObject<Swipeable> | null>(null);
do we still need `Swipeable`?

2024-09-06 06:41 UTC, sagark1510 commented on app/(protected)/(tabs)/leads.tsx
>    const [filterCount, setFilterCount] = useState(0);
you don't need to set filter count.. derive it run time.
```
filterCount = useMemo(() => {
 // TODO: add filter count logic
}, [filters]);
```

2024-09-06 06:42 UTC, sagark1510 commented on app/(protected)/(tabs)/leads.tsx
>      setDeleteCardId(slug);
setDeleteLeadId

2024-09-06 06:42 UTC, sagark1510 commented on app/(protected)/(tabs)/products.tsx
>  import { FlatListCon } from './tabs.style';
FlatListCon ?? rename

2024-09-06 06:43 UTC, sagark1510 commented on app/(protected)/(tabs)/products.tsx
> +  const [deleteId, setDeleteId] = useState(0);
deleteId of what?

2024-09-06 06:44 UTC, sagark1510 commented on app/(protected)/(tabs)/products.tsx
> +      setDeleteId={setDeleteId}
never pass state change actions directly.

onChangeDeleteId={(id) => setDeleteId(id)}

2024-09-06 06:45 UTC, sagark1510 commented on app/(protected)/(tabs)/users.tsx
>    const [refreshing, setRefreshing] = useState(false);
as you can see we have 3 different loading variables we should optimize it.

`const [loadingStatus, setLoadingStatus] = useState<'NONE' | 'DELETE' | 'MORE' | 'REFRESH'>('NONE');`

2024-09-06 06:46 UTC, sagark1510 commented on app/(protected)/(tabs)/users.tsx
> +        setShowModal={setShowModal}
remove all set actions from props

2024-09-06 06:48 UTC, sagark1510 commented on app/(protected)/(tabs)/users.tsx
> +  const renderUsers = ({
renderUsers = renderUser

2024-09-06 06:53 UTC, sagark1510 commented on components/molecules/ActionModal/ActionModal.styles.ts
> +      ? theme.colors.BlueChaos
why is this resolved? I still see the changes are not reflected.

2024-09-06 06:54 UTC, sagark1510 commented on components/molecules/ActionModal/ActionModal.styles.ts
> +      : actionType === Actions.default
No nested ternary

2024-09-06 06:56 UTC, sagark1510 commented on lib/utils/common.ts
> +    console.error('Failed to open dialer', err);
inform user about the failure

2024-09-09 05:54 UTC, sagark1510 approved these changes

2024-09-09 06:10 UTC, merged