Feature/kp/product service design 2
trentiums/expo-crm pull request #21
Opened 2024-09-11 05:38 UTC by kuldip-trentium

![Screenshot_20240911-110623_CRM](https://github.com/user-attachments/assets/bb41c020-77ea-4cbc-a304-929afcbff147)
![Screenshot_20240911-110631_CRM](https://github.com/user-attachments/assets/d1b486c3-42b8-4b9a-8f80-6118d2e8282b)
![Screenshot_20240911-110151_CRM](https://github.com/user-attachments/assets/207b0112-7f6f-4da1-acdc-ca51b270fdce)

2024-09-11 06:32 UTC, Deeptrentium requested changes

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +import Delete from '@atoms/Illustrations/Delete';
DeleteIcon

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +  const [deleteShowModal, setDeleteShowModal] = useState<Boolean>(false);
deleteShowModal = visibleDeleteModal

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +  const [deleteLoading, setDeleteLoading] = useState(false);
deleteLoader

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +        console.log('cancelled');
add toast error

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +    const deletedDocument = documentArray?.filter(
wrap this with if condition

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +import ProductServices from '@atoms/Illustrations/ProductService';
icon

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +              onPress={() => handlePhoneCall(leadData?.phone)}>
remove ?

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +              onPress={() => handleWhatsApp(leadData?.phone)}>
remove?

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/LeadDetail/LeadDetail.tsx
> +            optionType: ScreenOptionType.DEFAULT,
make from props

2024-09-11 06:32 UTC, Deeptrentium commented on components/molecules/ProductCard/ProductCard.tsx
> +            leadId: data?.id,
its a product id not lead id

2024-09-11 06:32 UTC, Deeptrentium commented on components/organisms/UserInformationForm/UserInformationForm.tsx
>    const [isActivePassword, setIsActivePassword] = useState(false);
remove this

2024-09-11 06:32 UTC, Deeptrentium commented on components/organisms/UserInformationForm/UserInformationForm.tsx
>                color={isActivePassword ? colors.primaryColor : colors.gray}
remove this

2024-09-11 11:27 UTC, Deeptrentium approved these changes

2024-09-12 06:16 UTC, Deeptrentium requested changes

2024-09-12 06:16 UTC, Deeptrentium commented on app/(protected)/add-product/[slug].tsx
> +  const [documentArray, setDocumentArray] = useState<fileSystemProps[]>([]);
fileSystemProps = FileSystemProps

2024-09-12 06:16 UTC, Deeptrentium commented on app/(protected)/add-product/[slug].tsx
> +          uri: documentArray?.[0]?.uri,
remove ?

2024-09-12 06:16 UTC, Deeptrentium commented on app/(protected)/add-product/[slug].tsx
> +          uri: documentArray?.[0]?.uri,
remove ?

2024-09-12 06:16 UTC, Deeptrentium commented on app/(protected)/add-product/add.tsx
> +  const [documentArray, setDocumentArray] = useState<fileSystemProps[]>([]);
fileSystemProps = FileSystemProps

2024-09-12 06:16 UTC, Deeptrentium commented on app/(protected)/add-product/add.tsx
> +          name: documentArray?.[0]?.name,
remove ?

2024-09-12 06:16 UTC, Deeptrentium commented on components/atoms/TextInput/TextInput.styles.ts
> +export const InputErrorContainer = styled(View)<{ isError?: boolean }>`
isError = invalidValue

2024-09-12 06:16 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.props.ts
> +  documentArray: fileSystemProps[];
fileSystemProps = FileSystemProps

2024-09-12 06:16 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +import UploadCon from '@atoms/Illustrations/UploadCon';
what is con rename this and its Icon so add Icon in last

2024-09-12 06:16 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +  const renderFilePreview = (file: any) => {
add type instead of any

2024-09-12 06:16 UTC, Deeptrentium commented on components/molecules/DocumentPicker/DocumentPicker.tsx
> +      {documentArray?.length === 0 && (
documentArray?.length > 0 ? <></> : <></>

2024-09-12 06:16 UTC, Deeptrentium commented on components/organisms/AddProductForm/AddProductForm.tsx
> +import DocumentPick from '@molecules/DocumentPicker/DocumentPicker';
PickDocuments or DocumentsPicker

2024-09-12 06:16 UTC, Deeptrentium commented on lib/utils/common.ts
> +
remove this changes

2024-09-13 07:29 UTC, Deeptrentium approved these changes

2024-09-13 12:09 UTC, sagark1510 approved these changes

2024-09-13 12:12 UTC, merged