Feature/kp/lead stage card
trentiums/expo-crm pull request #27
Opened 2024-09-13 13:35 UTC by kuldip-trentium

dashboard admin api and UI created

2024-09-16 05:25 UTC, Deeptrentium requested changes

2024-09-16 05:25 UTC, Deeptrentium commented on app/(protected)/(tabs)/dashboard.tsx
> +                name="Romes Smith"
why we use static name ?

2024-09-16 05:25 UTC, Deeptrentium commented on components/molecules/CompanyDashboardCard/CompanyDashboardCard.tsx
> +        <UserName numberOfLines={1}>{name}</UserName>
UserNameText

2024-09-16 05:25 UTC, Deeptrentium commented on components/organisms/LeadsProgressChart/LeadsProgressChart.styles.ts
> +  width: 70%;
please check

2024-09-16 05:25 UTC, Deeptrentium commented on components/organisms/LeadsProgressChart/LeadsProgressChart.styles.ts
> +  width: 80%;
please check

2024-09-16 06:15 UTC, kuldip-trentium commented on app/(protected)/(tabs)/dashboard.tsx
> +                name="Romes Smith"
bcz api integration is not done

2024-09-16 08:21 UTC, Deeptrentium commented on app/(protected)/(tabs)/dashboard.tsx
> +                name="Romes Smith"
then lets add a api call

2024-09-16 08:23 UTC, Deeptrentium requested changes

2024-09-16 08:23 UTC, Deeptrentium commented on components/organisms/LeadsProgressChart/LeadsProgressChart.styles.ts
> +  max-width: 70%;
width 100% and max width 70% what dose its means ?

2024-09-16 08:23 UTC, Deeptrentium commented on app/(protected)/(tabs)/dashboard.tsx
> +                    progress: 0,
why 0 ?

2024-09-16 13:00 UTC, Deeptrentium approved these changes

2024-09-17 06:20 UTC, sagark1510 approved these changes

2024-09-17 06:24 UTC, merged